site_name: mattのnote
site_description: mattのnote
site_author: matt
site_url: https://imatt.top
strict: false

# Repository
repo_name: 'imattdu/imattdu.github.io'
repo_url: 'https://github.com/imattdu/imattdu.github.io'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2021 - 2023 mattのnote'

theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    edit: material/file-edit-outline
    repo: fontawesome/brands/github
  logo: images/matt.png
  favicon: images/favicon.ico
  palette:
    primary: white  
  features:
    # 实时加载
    - navigation.instant
    # tabs
    - navigation.tabs
    # 自动隐藏
    # - header.autohide
    # 返回顶部
    - navigation.top
    # 代码注释
    - content.code.annotate
    - search.highlight
    - search.suggest
    # 搜索共享
    - search.share
    # 根据目录更新url
    - navigation.tracking
    # 导航跟随
    - toc.follow
plugins:
  - search:
      # separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      separator: '[\s\u200b\-]'
      # jieba_dict_user: user_dict.txt
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: false
      enable_creation_date: false     
  # 所有者    
  - git-authors        


extra:
  disqus: 'imattdu'
  generator: false
  social:
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/
    - icon: fontawesome/brands/github
      link: https://github.com/imattdu  
# 内容选项卡
markdown_extensions:
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # 代码高亮配置
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # 自定义图标
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - base:
    - Getting Started: index.md
    - go:
      - base:
        - 安装: base/go/0base/0setup.md
        - 基础: base/go/0base/1base.md
        - 常用数据结构: base/go/0base/2data_structure.md
        - 函数: base/go/0base/3func.md
        - 结构体: base/go/0base/4struct.md
        - 错误: base/go/0base/7error.md
      - concurrent:
        - groutine: base/go/1concurrent/0groutine.md
        - runtime: base/go/1concurrent/1runtime.md
        - channel: base/go/1concurrent/2channel.md
        - 定时器: base/go/1concurrent/3定时器.md
        - select: base/go/1concurrent/4select.md
        - lock: base/go/1concurrent/5lock.md
        - sync: go/1concurrent/6sync.md
        - atomic: base/go/1concurrent/7atomic.md
      - lib:
        - string: go/2lib/0string.md
        - time: go/2lib/1time.md
        - flag: go/2lib/2flag.md
        - log: go/2lib/3log.md
        - io: go/2lib/4io.md
        - 反射: go/2lib/9反射.md
    - cpp:
      - 基础: cpp/1base.md
      - 字符串: cpp/2string.md
      - 数组: cpp/3array.md
      - 逻辑: cpp/4if.md
      - 循环: cpp/5while.md
      - 函数: cpp/6func.md
      - 类: cpp/7class.md
      - stl:
        - init: cpp/1stl/0init.md
        - stl: cpp/1stl/1stl.md
    - python:
      - python: base/python/python.md
      - flask: base/python/flask.md             
  - util:
    - linux:
      - centos安装: util/linux/centos安装.md
      - 常用软件安装: util/linux/常用软件安装.md
    - mac:
      - 基本使用: util/mac/0基本使用.md
      - app: util/mac/app.md
      - iterm2: util/mac/iterm2.md
    - dev:
      - git: util/dev/git.md
      - jetBrains: util/dev/jetBrains.md
      - jetBrains_快捷键: util/dev/jetBrains_快捷键.md  
  - cs:
    - index:
      - index: cs.md
  - algo:
    - 基础:
      - 基础算法: algo/base/0基础算法.md
      - 数据结构: algo/base/1数据结构.md
      - 搜索与图论: algo/base/2搜索与图论.md
      - 数学: algo/base/3数学.md
      - dp: algo/base/4dp.md
  - db:
    - mysql:
      - 安装: db/00mysql-基础/0-init.md
      - 1-基础: db/00mysql-基础/1-基础.md
      - 10-创建表和管理表: db/00mysql-基础/10-创建表和管理表.md
      - 11-数据增删改: db/00mysql-基础/11-数据增删改.md
      - 12-数据类型: db/00mysql-基础/12-数据类型.md
      - 13-约束: db/00mysql-基础/13-约束.md
      - 14-视图: db/00mysql-基础/14-视图.md
      - 15-存储过程和函数: db/00mysql-基础/15-存储过程和函数.md
  - web:
    - gin:
      - base: web/gin/base.md
  - microservices:
    - index:
      - index: ms.md
  - mq:
    - kafka:
      - overview: mq/kafka/overview.md
      - install: mq/kafka/install.md
      - api: mq/kafka/api.md
      - client: mq/kafka/client.md   
  - bigdata:
    - hadoop:
      - overview: bigdata/hadoop/overview.md
      - quickstart: bigdata/hadoop/quickstart.md
      - hdfs: bigdata/hadoop/hdfs.md
      - mapreduce: bigdata/hadoop/mapreduce.md
    - flink:
      - overview: bigdata/flink/overview.md
      - quickstart: bigdata/flink/quickstart.md
      - datastreamAPI: bigdata/flink/datastreamAPI.md
      - table: bigdata/flink/table.md
  - question:
    - question: 
      - question/question.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  

