site_name: mattのnote
site_description: mattのnote
site_author: matt
site_url: https://imatt.top
strict: false

# Repository
repo_name: 'imattdu/imattdu.github.io'
repo_url: 'https://github.com/imattdu/imattdu.github.io'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 mattのnote'

theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  logo: images/matt.png
  favicon: images/favicon.ico
  palette:
    primary: white  
  features:
    # 实时加载
    - navigation.instant
    # tabs
    - navigation.tabs
    # 自动隐藏
    # - header.autohide
    # 返回顶部
    - navigation.top
    # 代码注释
    - content.code.annotate
    - search.highlight
    - search.suggest
    # 搜索共享
    - search.share
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: false
      enable_creation_date: false     
  - git-committers:
      repository: imattdu/imattdu.github.io
      token: !ENV GH_TOKEN
  - git-authors        


extra:
  disqus: 'imattdu'
  generator: false
  social:
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/
    - icon: fontawesome/brands/github
      link: https://github.com/imattdu  
# 内容选项卡
markdown_extensions:
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # 代码高亮配置
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # 自定义图标
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - 基础:
    - Getting Started: index.md
    - go:
      - base:
        - 安装: 00go/0base/0setup.md
        - 基础: 00go/0base/1base.md
        - 常用数据结构: 00go/0base/2data_structure.md
        - 函数: 00go/0base/3func.md
        - 结构体: 00go/0base/4struct.md
        - 错误: 00go/0base/7error.md
      - concurrent:
        - groutine: 00go/1concurrent/0groutine.md
        - runtime: 00go/1concurrent/1runtime.md
        - channel: 00go/1concurrent/2channel.md
        - 定时器: 00go/1concurrent/3定时器.md
        - select: 00go/1concurrent/4select.md
        - lock: 00go/1concurrent/5lock.md
        - sync: 00go/1concurrent/6sync.md
        - atomic: 00go/1concurrent/7atomic.md
      - lib:
        - string: 00go/2lib/0string.md
        - time: 00go/2lib/1time.md
        - flag: 00go/2lib/2flag.md
        - log: 00go/2lib/3log.md
        - io: 00go/2lib/4io.md
        - 反射: 00go/2lib/9反射.md
    - cpp:
      - 基础: 02cpp/1base.md
      - 字符串: 02cpp/2string.md
      - 数组: 02cpp/3array.md
      - 逻辑: 02cpp/4if.md
      - 循环: 02cpp/5while.md
      - 函数: 02cpp/6func.md
      - 类: 02cpp/7class.md
      - stl:
        - init: 02cpp/1stl/0init.md
        - stl: 02cpp/1stl/1stl.md
    - python:
      - python: 03python/python.md
      - 字符串: 03python/flask.md    
         
  - 工具:
    - mac:
      - 基本使用: 09tool/1mac/0基本使用.md
      - 常用软件: 09tool/1mac/1常用软件.md
      - iterm2美化: 09tool/1mac/2iterm2美化.md
    - dev:
      - git: 09tool/3dev/git.md
      - jetBrains: 09tool/3dev/jetBrains.md
      - jetBrains_快捷键: 09tool/3dev/jetBrains_快捷键.md  
  - 算法:
    - 基础:
      - 基础算法: 10algorithm/base/0基础算法.md
      - 数据结构: 10algorithm/base/1数据结构.md
      - 搜索与图论: 10algorithm/base/2搜索与图论.md
      - 数学: 10algorithm/base/3数学.md
      - dp: 10algorithm/base/4dp.md
  - db:
    - mysql:
      - 安装: 20db/00mysql-基础/0-init.md
      - 1-基础: 20db/00mysql-基础/1-基础.md
      - 10-创建表和管理表: 20db/00mysql-基础/10-创建表和管理表.md
      - 11-数据增删改: 20db/00mysql-基础/11-数据增删改.md
      - 12-数据类型: 20db/00mysql-基础/12-数据类型.md
      - 13-约束: 20db/00mysql-基础/13-约束.md
      - 14-视图: 20db/00mysql-基础/14-视图.md
  - web:
    - gin:
      - base: 23frame/gin/base.md
  - 中间件:
    - redis:
      - 安装: 34mw/0redis/0setup.md
      - 基础: 34mw/0redis/1base.md
      - 提高: 34mw/0redis/2advanced.md
      - 源码: 34mw/0redis/3source.md
      - API: 34mw/0redis/4api.md
    - kafka:
      - 概述: 33mq/0kafka/0概述.md
      - 安装: 33mq/0kafka/1安装.md
    - zookeeper:
      - zookeeper学习: 34mw/zookeeper/zookeeper学习.md
    - es:
      - 基础: 34mw/es/es基础.md    


extra_css:
  - stylesheets/extra.css

