 name: ci 
on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip3 install mkdocs-material 
      - run: pip3 install mkdocs-git-revision-date-localized-plugin
      # - run: pip3 install mkdocs-git-committers-plugin-2
      - run: pip3 install mkdocs-git-authors-plugin
      - run: pip3 install lxml
      - run: pip3 install jieba
      - run: mkdocs gh-deploy --force
